# run on container environment
sudo: true

language: php

php: 7.2
    
script:
    - ls
    - cd ../../
    - git clone https://github.com/johnbillion/extended-cpts.git
    - ls
    - cd extended-cpts
    - ls
    - cp src/* ../vsp-libs/extended-cpts/src/
    - cp functions.php ../vsp-libs/extended-cpts/functions.php
    - cp extended-cpts.php ../vsp-libs/extended-cpts/extended-cpts.php
    - cd ../
    - ls
    - yes
    - cd vsp-libs/extended-cpts/
    - ls
